name: biblioteca_digital
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: ^3.9.2  
# ESTO ES LO QUE DEBE ESTAR IGUAL EN TODOS LOS COMPUTADOSES LA VERSIOIN SDK. 

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.3.0
  google_fonts: ^6.3.1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^7.2.0
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

